# Generated by Django 5.2.4 on 2025-07-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='id',
            new_name='id_reserva',
        ),
    ]
