# Generated by Django 5.2.4 on 2025-11-18 00:41

import SARC.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0002_add_user_columns'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', SARC.models.UsuarioManager()),
            ],
        ),
    ]
