# Generated by Django 5.2.4 on 2025-11-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0003_create_user_m2m_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='senha', max_length=128, verbose_name='password'),
        ),
    ]
