# Generated by Django 5.2.4 on 2025-08-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0003_sala_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id_computador', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SARC.sala')),
            ],
        ),
    ]
