# Generated by Django 5.2.4 on 2025-08-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0004_usuario_matricula_computador'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SARC.usuario'),
            preserve_default=False,
        ),
    ]
