# Generated by Django 5.2.4 on 2025-11-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0005_alter_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
