# Generated by Django 5.2.4 on 2026-06-07 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0006_remove_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='bloqueio',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DiaBloqueado',
            fields=[
                ('bloqueio_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(unique=True)),
                ('motivo', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
