# Generated by Django 5.2.4 on 2025-10-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0006_computador_estado_reserva_computador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('bolsista', 'Bolsista'), ('aluno', 'Aluno'), ('professor', 'Professor')], default='aluno', max_length=10),
        ),
    ]
