# Generated by Django 5.2.7 on 2025-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0006_computador_estado_reserva_computador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno'), ('bolsista', 'Bolsista')], default='aluno', max_length=20),
        ),
    ]
