# Generated by Django 6.0.4 on 2026-06-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0007_notificacao'),
        ('SARC', '0007_reserva_bloqueio_diabloqueado'),
    ]

    operations = [
    ]
