# Generated by Django 5.2.4 on 2025-10-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0007_usuario_funcao'),
        ('SARC', '0007_usuario_tipo_usuario'),
    ]

    operations = [
    ]
