# Generated by Django 5.2.4 on 2026-08-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('SARC', '0008_merge_20260630_1121')]

    operations = [
        migrations.CreateModel(name='Projeto', fields=[
            ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
            ('titulo', models.CharField(max_length=150)), ('descricao', models.TextField()),
            ('data_inicio', models.DateField()), ('data_limite', models.DateField()),
            ('criado_em', models.DateTimeField(auto_now_add=True)),
            ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
            ('participantes', models.ManyToManyField(related_name='projetos', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering': ['data_limite', '-criado_em']}),
        migrations.CreateModel(name='AnotacaoProjeto', fields=[
            ('id_anotacao', models.AutoField(primary_key=True, serialize=False)), ('conteudo', models.TextField()),
            ('criado_em', models.DateTimeField(auto_now_add=True)),
            ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes_de_projeto', to=settings.AUTH_USER_MODEL)),
            ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='SARC.projeto')),
        ], options={'ordering': ['-criado_em']}),
        migrations.CreateModel(name='ArquivoProjeto', fields=[
            ('id_arquivo', models.AutoField(primary_key=True, serialize=False)), ('arquivo', models.FileField(upload_to='projetos/%Y/%m/')),
            ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_de_projeto', to=settings.AUTH_USER_MODEL)),
            ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='SARC.projeto')),
        ], options={'ordering': ['-enviado_em']}),
    ]
