# Generated by Django 5.2.3 on 2025-10-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0008_merge_0007_usuario_funcao_0007_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='funcao',
        ),
    ]
