# Generated by Django 6.1.1 on 2026-09-30 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0009_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='descricao',
            field=models.TextField(blank=True, help_text="Descrição da sala - obrigatória se tipo é 'Outro'", null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('laboratorio_informatica', 'Laboratório de Informática'), ('sala_aula', 'Sala de Aula'), ('outro', 'Outro')], default='laboratorio_informatica', max_length=30),
        ),
        migrations.CreateModel(
            name='SalaGenérica',
            fields=[
                ('id_sala_generica', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField(help_text='Capacidade máxima de alunos')),
                ('tipo', models.CharField(choices=[('sala_aula', 'Sala de Aula'), ('sala_reuniao', 'Sala de Reunião'), ('auditorio', 'Auditório'), ('outro', 'Outro')], default='sala_aula', max_length=30)),
                ('descricao', models.TextField(blank=True, help_text="Descrição da sala - obrigatória se tipo é 'Outro'", null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sala Genérica',
                'verbose_name_plural': 'Salas Genéricas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ReservaSalaGenérica',
            fields=[
                ('id_reserva_generica', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('motivo', models.TextField(help_text='Motivo/descrição da reserva')),
                ('numero_alunos', models.IntegerField(default=1, help_text='Número estimado de alunos')),
                ('presenca', models.CharField(choices=[('pendente', 'Pendente'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='pendente', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_salas_genericas', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='SARC.salagenérica')),
            ],
            options={
                'verbose_name': 'Reserva de Sala Genérica',
                'verbose_name_plural': 'Reservas de Salas Genéricas',
                'ordering': ['-data', '-horario'],
                'unique_together': {('sala', 'data', 'horario')},
            },
        ),
    ]
