# Generated by Django 5.2.7 on 2025-10-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0009_remove_usuario_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='presenca',
            field=models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('pendente', 'Pendente')], default='pendente', max_length=10),
        ),
    ]
