# Generated by Django 5.2.4 on 2025-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('sala', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('presenca', models.BooleanField(default=False)),
            ],
        ),
    ]
