# Generated by Django 5.2.3 on 2025-09-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARC', '0005_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='estado',
            field=models.CharField(default='Disponível', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='computador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SARC.computador'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SARC.sala'),
        ),
    ]
